name: Continuous Integration (Run lint and test)

on: [pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Install dependencies
        run: cd frontend && npm install

      - name: Lint
        run: cd frontend && npm run lint

      - name: Test
        run: cd frontend && npm run test
